# Generated by Django 5.2.8 on 2025-12-01 22:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import plataforma.validador
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('consumidor', 'Consumidor'), ('proveedor', 'Proveedor de leña'), ('servicio', 'Prestador de servicios'), ('ambos', 'Ambos (leña y servicios)')], default='consumidor', max_length=20)),
                ('rut', models.CharField(blank=True, help_text='Formato: 12.345.678-5', max_length=12, null=True, validators=[plataforma.validador.validar_rut_chileno])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='plataforma.comuna')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='plataforma.region')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('resumen', models.TextField(blank=True)),
                ('texto', models.TextField()),
                ('tema', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenido educativo',
                'verbose_name_plural': 'Contenidos educativos',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion_texto', models.CharField(blank=True, max_length=255)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('recibe_boletin', models.BooleanField(default=False)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='plataforma.comuna')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('rut', models.CharField(help_text='Formato: 12.345.678-5', max_length=12, unique=True, validators=[plataforma.validador.validar_rut_chileno])),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('direccion_texto', models.CharField(max_length=255)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('numero_sncl', models.CharField(help_text='Número de registro SNCL', max_length=50)),
                ('es_proveedor_biocombustible', models.BooleanField(default=False)),
                ('es_prestador_servicios', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='plataforma.comuna')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor / Prestador',
                'verbose_name_plural': 'Proveedores / Prestadores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('LENA', 'Leña'), ('PELLET', 'Pellet'), ('BRIQUETA', 'Briqueta'), ('CARBON', 'Carbón')], max_length=20)),
                ('especie', models.CharField(blank=True, max_length=100)),
                ('contenido_humedad', models.FloatField(blank=True, help_text='Porcentaje aproximado de humedad', null=True)),
                ('formato', models.CharField(help_text='Ej: m³, saco 20kg, etc.', max_length=100)),
                ('unidad_medida', models.CharField(help_text='Ej: m3, kg, saco', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('stock_disponible', models.IntegerField(blank=True, null=True)),
                ('certificado_sncl', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='plataforma.comuna')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='plataforma.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='QuizIntentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.PositiveIntegerField()),
                ('total_preguntas', models.PositiveIntegerField()),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='plataforma.contenidoeducativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de quiz',
                'verbose_name_plural': 'Intentos de quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('OPCION_MULTIPLE', 'Opción múltiple'), ('VERDADERO_FALSO', 'Verdadero/Falso')], default='OPCION_MULTIPLE', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='plataforma.contenidoeducativo')),
            ],
            options={
                'verbose_name': 'Pregunta de quiz',
                'verbose_name_plural': 'Preguntas de quiz',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='QuizOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='plataforma.quizpregunta')),
            ],
            options={
                'verbose_name': 'Opción de quiz',
                'verbose_name_plural': 'Opciones de quiz',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='plataforma.region'),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_moderacion', models.DateTimeField(blank=True, null=True)),
                ('moderado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas_moderadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='plataforma.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('CORTE', 'Corte de leña'), ('PICADO', 'Picado / trozado'), ('TRANSPORTE', 'Transporte'), ('LIMPIEZA_CANALES', 'Limpieza de estufas / cañones')], max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_precio', models.CharField(help_text='Ej: viaje, hora, m3 transportado', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comunas_cobertura', models.ManyToManyField(blank=True, related_name='servicios_disponibles', to='plataforma.comuna')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='plataforma.proveedor')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='SolicitudRolComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('PROVEEDOR', 'Proveedor de biocombustibles'), ('PRESTADOR', 'Prestador de servicios'), ('AMBOS', 'Proveedor y prestador')], default='PROVEEDOR', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True)),
                ('nombre_comercio', models.CharField(blank=True, help_text='Nombre del comercio para venta de biocombustibles', max_length=255)),
                ('giro_comercial', models.CharField(blank=True, help_text='Ej: Venta de leña seca', max_length=255)),
                ('direccion_punto_venta', models.CharField(blank=True, help_text='Dirección o punto de venta', max_length=255)),
                ('acepta_ley_biocombustibles', models.BooleanField(default=False, help_text='Marca si declara cumplir la Ley de Biocombustibles')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad principal donde presta servicios', max_length=100)),
                ('datos_contacto', models.CharField(blank=True, help_text='Teléfono y/o correo de contacto', max_length=255)),
                ('tipo_servicios', models.CharField(blank=True, help_text='Ej: Transporte, instalación de calefactor, limpieza de cañones', max_length=255)),
                ('acepta_terminos', models.BooleanField(default=False, help_text='Acepta los términos y condiciones del sitio')),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de rol comercial',
                'verbose_name_plural': 'Solicitudes de rol comercial',
            },
        ),
        migrations.CreateModel(
            name='TarifaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_por_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifas_envio', to='plataforma.comuna')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_envio', to='plataforma.proveedor')),
            ],
            options={
                'verbose_name': 'Tarifa de envío',
                'verbose_name_plural': 'Tarifas de envío',
            },
        ),
    ]
