# Generated by Django 5.2.8 on 2025-12-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_usuario_bloqueado_usuario_email_verificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='formato',
            field=models.CharField(choices=[('METRO_RUMA', 'Metro ruma'), ('M3_GRANEL', 'm³ a granel'), ('SACO_15', 'Saco 15 kg'), ('SACO_20', 'Saco 20 kg'), ('SACO_25', 'Saco 25 kg'), ('BOLSA', 'Bolsa'), ('OTRO', 'Otro')], help_text='Presentación del producto', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('m3', 'm³'), ('saco', 'Saco'), ('kg', 'Kilogramo'), ('bolsa', 'Bolsa'), ('pallet', 'Pallet')], help_text='Unidad de cobro', max_length=20),
        ),
    ]
